### ISSUE TITLE
Any support for pg-14 backup?

### ISSUE THREAD

**Issue by msarm** [mccarthysean/TimescaleDB-Backup-S3#1]
Would like to know any support for pg-14 backup?

**Comment by mccarthysean** [comment]
Should work fine if you just change 13 to 14 everywhere you see it. I haven't pushed an image to Docker Hub for v14, but you could do that too if you want 👍

I'm on holidays for a few days   :)

**Comment by mccarthysean** [comment]
FYI, I've added support for Postgres v14. `docker pull mccarthysean/timescaledb_backup_s3:latest-14`
